version: "3.9"
services:
    hadoop01:
        image: hadoop-base:latest
        volumes:
          - ./etc-hadoop:/etc-hadoop
          - ./conf-hive:/conf-hive
        environment:
          - HADOOP_CONF_DIR=/etc-hadoop
          - HIVE_CONF_DIR=/conf-hive
        networks:
          - hadoop-net
        hostname: hadoop01
        tty: true
        ports:
          - "9870:9870"
          - "8088:8088"
          - "19888:19888"
    hadoop02:
        image: hadoop-base:latest
        environment:
          - HADOOP_CONF_DIR=/etc-hadoop
          - HIVE_CONF_DIR=/conf-hive
        volumes:
          - ./etc-hadoop:/etc-hadoop
          - ./conf-hive:/conf-hive
        networks:
          - hadoop-net
        hostname: hadoop02
        tty: true
        ports:
          - "9868:9868"
    hadoop03:
        image: hadoop-base:latest
        environment:
          - HADOOP_CONF_DIR=/etc-hadoop
          - HIVE_CONF_DIR=/conf-hive
        volumes:
          - ./etc-hadoop:/etc-hadoop
          - ./conf-hive:/conf-hive
        networks:
          - hadoop-net
        hostname: hadoop03
        tty: true
    mysql:
        image: mysql:8.0.28
        networks:
          - hadoop-net
        hostname: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: yhy
            MYSQL_USER: yhy
            MYSQL_PASSWORD: my-secret-pw
networks:
    hadoop-net:
        driver: bridge
